# Generated by Django 4.1.5 on 2023-05-04 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_created=True)),
                ('reference', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=500)),
                ('price', models.FloatField()),
                ('vat', models.FloatField()),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ordering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_created=True)),
                ('total_price', models.FloatField()),
                ('total_price_vta', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderingArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.IntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_orders', to='inventory.article')),
                ('ordering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordering_articles', to='inventory.ordering')),
            ],
        ),
    ]
