# Generated by Django 4.1.5 on 2023-05-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_article_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='creation_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
