# Generated by Django 4.1.5 on 2023-05-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_article_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordering',
            name='creation_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordering',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordering',
            name='total_price_vta',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
