# Generated by Django 4.1.5 on 2023-05-08 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_ordering_creation_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderingarticle',
            old_name='cant',
            new_name='amount',
        ),
    ]
