# Generated by Django 4.1.5 on 2023-05-09 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_cant_orderingarticle_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordering',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='ordering',
            name='total_price_vta',
        ),
        migrations.AddField(
            model_name='orderingarticle',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderingarticle',
            name='total_price_vta',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
