# Generated by Django 4.1.5 on 2023-05-09 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_ordering_total_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderingarticle',
            old_name='total_price_vta',
            new_name='total_price_vat',
        ),
    ]
